from kedro.framework.context import KedroContext
from kedro.config.config import MissingConfigException


def get_monitor_config(context: KedroContext, tool: str):
    try:
        conf_monitor = context.config_loader.get(f"{tool}*", f"{tool}*/**")
    except MissingConfigException as e:
        print(e)
        print("Check the config files were generated by new command")
        exit(1)
    return conf_monitor
